
  services:
    mongo-server:
      image: mongo:latest
      container_name: mongo-server
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - mongodb-data:/data/db
      networks:
        mongodb-network:
          ipv4_address: 172.28.0.30
    mongo-client: 
      image: mongo-express:latest
      container_name: mongo-client
      restart: always
      depends_on:
        - mongo-server
      environment:
        - ME_CONFIG_MONGODB_SERVER=mongo-server
        - ME_CONFIG_MONGODB_PORT=27017
      ports:
        - "8081:8081"
      networks:
        mongodb-network:
          ipv4_address: 172.28.0.20
    web-server:
      image: web_server
      container_name: web-server
      restart: always
      depends_on:
        - mongo-server
      ports:
        - "80:80"
      networks:
        mongodb-network:
          ipv4_address: 172.28.0.10
  
  volumes:
    mongodb-data:
  
  networks:
    mongodb-network:
      driver: bridge
      ipam:
        config:
          - subnet: 172.28.0.0/16
            gateway: 172.28.0.1

  
